repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        files: '\.(py|ipynb)$'
      - id: ruff-format
        files: '\.(py|ipynb)$'

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        files: '\.(py|ipynb)$'
